"""ゲームルール定数・勝敗判定"""

# ゲーム基本設定
INITIAL_MONEY = 3000
GOAL_ASSETS = 10000
MAX_CARDS = 7
DICE_MIN = 1
DICE_MAX = 6

# 経営コマンドコスト
EDUCATION_COST_PER_EMPLOYEE = 15
EDUCATION_ABILITY_GAIN = 20
ADVERTISING_COST = 200
ADVERTISING_FAME_GAIN = 20
HIRE_COST_PER_PERSON = 15

# パラメータ上下限
ABILITY_MAX = 100
ABILITY_MIN = 0
FAME_MAX = 100
FAME_MIN = 0

# 偶数ターン減衰
ABILITY_DECAY = 2
FAME_DECAY = 2

# 使用料率
COMPANY_FEE_RATE = 0.30
LAND_FEE_RATE = 0.20

# 土地購入倍率
LAND_BUYOUT_MULTIPLIER = 5
COMPANY_BUYOUT_MULTIPLIER = 4

# 売却レート
SELL_RATE = 0.5
CARD_SELL_RATE = 0.2

# 戦闘
FLEE_DIVISOR = 300
FLEE_PENALTY_RATE = 0.05
DAMAGE_RANDOM_RANGE = 0.20
DEFENSE_MULTIPLIER = 5
MIN_DAMAGE = 1

# のんびりカード
SLOW_DEBUFF_TURNS = 5

# ニュース
NEWS_INTERVAL = 5

# 画面サイズ
SCREEN_WIDTH = 512
SCREEN_HEIGHT = 512
TILE_SIZE = 32
PLAYER_SPRITE_W = 16
PLAYER_SPRITE_H = 16
FPS = 30
